### PR TITLE
Guess cucumber package name - support for cucumber 7

### LINKED ISSUE #191: Cucumber version deprecated, please update this project to latest version
Hi Team,

Cucumber has been deprecated and now it is @cucumber/cucumber and the version is 7.0.0 would you please update this repo to reflect
Npm_cucumber
 to latest

### PR DESCRIPTION
**Pull request by beradrian**
Fixes #191

### CODE REVIEW

**Comment by c16a** [comment]
@AlexandrosD can this please be merged? This is a fix for #191

**Comment by AlexandrosD** [comment]
See https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/73#issuecomment-762493006

**Comment by flaviencathala** [comment]
@beradrian does your fix fully work? I mean that Cucumber 7 breaks the events API and the results capture doesn't seem to work anymore. The visible effect is that the program exits with an error code even if all tests are successful.

**Comment by flaviencathala** [comment]
@beradrian I have submitted another PR based on this one. Feel free to cherry pick my fix for this PR if you prefer to use this one.

**Comment by beradrian** [comment]
I tested on a project that I work on and it seems to work.

**Comment by flaviencathala** [comment]
@beradrian so in your project when all the tests pass the exit code is 0? That's odd.

**Comment by beradrian** [comment]
@flaviencathala actually you're right. We should use your PR.

**Comment by flaviencathala** [comment]
Should be fixed by https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/194

**Pull request closed without merging**
