### PR TITLE
Adding `progress` to eventDetails

### PR DESCRIPTION
**Pull request by phenomnomnominal**
Here's a very basic implementation of what is discussed in #105 
We can discuss the specifics of the data we want to pass back in the event, and once that's finalised I'll add some tests.

### CODE REVIEW

**Comment by darrinholst** [comment]
Looks OK to me

**Comment by darrinholst** [comment]
If you want to add some tests for this I'll merge it in.

**Comment by phenomnomnominal** [comment]
Oh yeah! Sorry this slipped off my radar, I’ll sort them out today!

**Comment by phenomnomnominal** [comment]
Just sat down to try and write some tests, and I'm a bit confused by what my approach should be. Any pointers? There doesn't seem to be any other tests over this kind of functionality.

**Comment by darrinholst** [comment]
I think you’ll want the `expectEvents` assertion. Check out https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/test/source-location.spec.js

**Pull request merged**
