### PR TITLE
Update PCF to not report failures for retryable steps

### PR DESCRIPTION
**Pull request by achuinard**

### CODE REVIEW

**Comment by Phonesis** [comment]
Be amazing to see this merged soon! Really causing problems where I work too

**Comment by Phonesis** [comment]
can a new github version release be created for this now it's on master?

**Comment by jdanemlig** [comment]
> can a new github version release be created for this now it's on master?

Not that I disagree with you, but Isn't it enough to delete the package from "cache" and let it redownload?

**Comment by Phonesis** [comment]
> > can a new github version release be created for this now it's on master?
> 
> Not that I disagree with you, but Isn't it enough to delete the package from "cache" and let it redownload?

No I don't think so, unless missing something. The fix is on master now but not the current 6.2.0 release branch? So when we download via npm it will just get 6.2.0 without the fix in place?

**Comment by AlexandrosD** [comment]
Guys, hold your horses a bit.

The fix is in master, meaning it will be part of the next released version. It doesn't get automatically to any release/version.

v6.2.0 does not include this fix. A new version is needed.

A new version will be created, and a new npm package will be published.
I will try to release v6.2.1 with only this change, this weekend.

**Pull request merged**
